### ISSUE TITLE
Can you elaborate the hardware setup in depth?

### ISSUE THREAD

**Issue by fuatakgun** [jacobstim/comfoairclient-arduino#1]
Thank you for setting this up. I have an Arduino board and Zehnder Comfoair q450 ventilation unit and i would like to communicate with ventilation unit. Can you please elaborate hardware setup more? A photo also would be great.

By the way, i am planning to connect my ventilation unit using RJ45 plug rather than RS232 port. I see that the pins are defined for RJ45 connection.

**Comment by jacobstim** [comment]
The hardware setup is conceptually not so complex: the ComfoD series have an on-board 9-pin serial connector (-12V to +12V) which, once converted to TTL voltage levels (0-5V / 0-3,3V) can be read directly from a microcontroller's serial port. In order to do the level conversion, I recommend using one of the standard MAX232 (5V TTL) / MAX3232 (3V TTL) breakout boards, such as [Sparkfun's board](https://www.sparkfun.com/products/11189). 

For the ComfoAir, I am not sure if the newer machines follow the same specifications as the ComfoD units (my suspicion grows if I read [this thread](https://community.openhab.org/t/zehnder-comfoairq350-do-i-need-comfoconnect-to-control-it/13159/13)). I have no such unit accessible to test so unfortunately I cannot confirm that this would work for the ComfoAir machines. 

Please keep us posted on your experiments!

**Comment by fuatakgun** [comment]
You were right about different specifications, my machine has 2 CAN bus and one RJ45 connection which is reserved for CAN diagnostics. I qas able to find 12v from RJ45 cables but order is different than previous devices.

I found another repository ( https://github.com/marco-hoyer/zcan ) to read from CAN bus but it requires full fledged Raspberry PI because it runs on python and using usb as input.

Thanks for guidance
